# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

# Database connectivity
spring.datasource.url=jdbc:postgresql://postgresdb:5432/postgres
spring.datasource.username=conductor
spring.datasource.password=conductor


# Indexing Properties
conductor.indexing.enabled=true
conductor.indexing.type=postgres
# Required to disable connecting to elasticsearch.
conductor.elasticsearch.version=0

# Additional modules for metrics collection exposed to Prometheus (optional)
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen-sink workflow
loadSample=true

conductor.message-publisher.type=rabbitmq
conductor.message-publisher.rabbitmq.hosts=rabbitmq
conductor.message-publisher.rabbitmq.username=guest
conductor.message-publisher.rabbitmq.password=guest
conductor.message-publisher.rabbitmq.port=5672
conductor.message-publisher.rabbitmq.workflowStatusExchange=workflow.status.exchange
conductor.message-publisher.rabbitmq.taskStatusExchange=task.status.exchange
conductor.message-publisher.rabbitmq.workflowStatusListenerEnabled=true
conductor.message-publisher.rabbitmq.allowedTaskStatuses=COMPLETED,IN_PROGRESS,FAILED
conductor.workflow-status-listener.type=rabbitmq
conductor.task-status-listener.type=rabbitmq